/**
 * Domain model — what a "model" IS in this system (PRD §6).
 *
 * A model is a typed, semantic object graph — a set of time-aware series and
 * drivers wired by formulas — NOT an opaque grid of cells. These types are the
 * contract every adapter (UI, AdonisJS API, MCP server) speaks in.
 */

export type Granularity = "monthly" | "quarterly" | "annual";

export type Unit =
  | "currency"
  | "percent"
  | "count"
  | "ratio"
  | "per_unit"
  | "none";

/** Semantic category of a line item — what statement/role it plays. */
export type ItemCategory =
  | "revenue"
  | "cogs"
  | "opex"
  | "headcount"
  | "asset"
  | "liability"
  | "equity"
  | "cashflow"
  | "kpi"
  | "other";

export type ModelType =
  | "blank"
  | "three_statement"
  | "dcf"
  | "lbo"
  | "saas"
  | "fpa"
  | "project_finance"
  | "real_estate"
  | "cohort"
  | "bitcoin_treasury";

/**
 * The time axis. `actualsThrough` is the index of the last period that holds
 * locked historical actuals; everything after it is forecast.
 */
export interface Timeline {
  granularity: Granularity;
  /** ISO date of the first period's start, e.g. "2026-01-01". */
  start: string;
  /** Number of periods on the axis. */
  periods: number;
  /** First fiscal month, 1-12. Jan = 1. */
  fiscalYearStartMonth: number;
  /** Index (0-based) of the last actuals period; -1 means all forecast. */
  actualsThrough: number;
}

/** An input definition: either literal values per period or a driver reference. */
export interface InputDefinition {
  kind: "input";
  /** Per-period values, aligned to the timeline. Nulls are treated as 0. */
  values: (number | null)[];
}

/** A formula definition: a time-aware expression over other items/drivers. */
export interface FormulaDefinition {
  kind: "formula";
  /** Expression source, e.g. "revenue * gross_margin" or "prior(cash) + net_income". */
  expression: string;
}

/** A driver-reference definition: the item mirrors a named driver's series. */
export interface DriverRefDefinition {
  kind: "driver_ref";
  driverId: string;
}

export type ItemDefinition =
  | InputDefinition
  | FormulaDefinition
  | DriverRefDefinition;

/** A named, typed time series — the atomic unit of the model. */
export interface LineItem {
  id: string;
  name: string;
  category: ItemCategory;
  unit: Unit;
  /** Optional section grouping, e.g. "revenue_build", "working_capital". */
  section?: string;
  definition: ItemDefinition;
  notes?: string;
  /**
   * Display magnitude for the item's values (e.g. 1_000_000 when values are in
   * $millions). Presentation metadata ONLY — never read by the engine and never
   * affects a computed value. Falls back to `ModelMeta.defaultScale`, then 1.
   */
  scale?: number;
  /**
   * The definition this item had before it was replayed from actuals (see
   * `replayActuals`). Preserved so the original formula can be restored.
   */
  replacedDefinition?: ItemDefinition;
}

export type DriverShape = "scalar" | "series" | "step" | "ramp";

/**
 * Binds a driver's series to a commodity price model (see commodities.ts). The
 * driver's `values` are GENERATED from the model over the timeline and can be
 * regenerated (notably when the timeline changes). Params override the model's
 * defaults key-by-key (e.g. `{ spot: 62850, band: "fair" }`).
 */
export interface CommodityPriceBinding {
  commodity: string;
  model: string;
  params: Record<string, number | string>;
}

/**
 * A distinguished input that feeds formulas but is not itself a statement line
 * (growth rate, price, churn, hiring plan, DSO/DPO, discount rate). Drivers are
 * what scenarios override and what sensitivities sweep.
 */
export interface Driver {
  id: string;
  name: string;
  unit: Unit;
  shape: DriverShape;
  /**
   * Base values per period. A scalar driver repeats value[0] across the axis;
   * step/ramp are expanded to a full series at load time.
   */
  values: number[];
  notes?: string;
  /** Optional: this driver's series is generated by a commodity price model. */
  priceModel?: CommodityPriceBinding;
  /**
   * Display magnitude for the driver's values (see `LineItem.scale`).
   * Presentation metadata ONLY — never affects computation.
   */
  scale?: number;
}

/** A named overlay of driver values. Base is always present and overrides nothing. */
export interface Scenario {
  id: string;
  name: string;
  /** driverId -> per-period override values (partial series allowed). */
  overrides: Record<string, (number | null)[]>;
  /**
   * Optional per-driver commodity price bindings scoped to this scenario. When set,
   * the driver's series is generated from these params and stored in `overrides`, so
   * this scenario computes its own price path. Absent → the driver inherits the base
   * (driver-level) price path. Remembered so the params can be re-adjusted.
   */
  priceModels?: Record<string, CommodityPriceBinding>;
}

export interface ModelMeta {
  name: string;
  type: ModelType;
  baseCurrency: string;
  createdAt: string;
  modifiedAt: string;
  version: number;
  /**
   * Default display magnitude for currency values that don't set their own
   * `scale` (e.g. 1_000_000 for a model kept in $millions). Presentation only.
   */
  defaultScale?: number;
  /**
   * Ticker of the company modeled by a ticker-aware template (e.g. the
   * `bitcoin_treasury` template stores the uppercased ticker here). Presentation
   * only — lets adapters display the company identity (e.g. uppercase the item
   * name prefix in tiles/rows) without re-deriving it from item names.
   */
  ticker?: string;
}

// ---------------------------------------------------------------------------
// Visualization: charts and dashboards
//
// These are persisted *definitions* on the model, never computed numbers. A
// chart names the series it plots (by item/driver name); its data is derived on
// demand for a scenario (see outputs.getChartData). A dashboard lays out widgets
// that reference charts, items, statements, or hold free text.
// ---------------------------------------------------------------------------

export type ChartKind = "line" | "area" | "bar" | "composed";

/** One plotted series in a chart, referencing a model item or driver by name. */
export interface ChartSeries {
  /** Item or driver name to plot (items win name collisions, per engine rules). */
  ref: string;
  /** Display label; defaults to `ref`. */
  label?: string;
  /** Which Y axis to bind to. Defaults to "left". */
  axis?: "left" | "right";
  /** Render style within the chart kind (e.g. "line" | "bar" | "area"). */
  style?: "line" | "bar" | "area";
  /** Rebase the series to 100 at the first period (for indexed comparisons). */
  index?: boolean;
}

/** A persisted chart definition. Stores no numeric data. */
export interface Chart {
  id: string;
  title: string;
  kind: ChartKind;
  /** Optional scenario to pin the chart to; otherwise the viewer's scenario. */
  scenarioId?: string;
  series: ChartSeries[];
  /** Free-form rendering options (axis formats, reference lines, etc.). */
  options?: Record<string, unknown>;
}

export type WidgetKind = "chart" | "stat" | "statement" | "note";

/** Grid placement on a fixed-column dashboard grid. */
export interface WidgetLayout {
  x: number;
  y: number;
  w: number;
  h: number;
}

/**
 * A dashboard widget. The meaning of `refId` depends on `kind`:
 * - "chart"     -> a Chart id
 * - "stat"      -> an item name (headline tile)
 * - "statement" -> a StatementKind ("income" | "balance_sheet" | "cash_flow" | "kpi")
 * - "note"      -> unused; text lives in `text`
 */
export interface Widget {
  id: string;
  kind: WidgetKind;
  refId?: string;
  /** Note text (kind === "note"). */
  text?: string;
  /** Optional per-widget title override. */
  title?: string;
  layout: WidgetLayout;
}

/** An ordered, editable set of widgets. */
export interface Dashboard {
  /** Number of columns on the layout grid. Defaults to 12. */
  columns?: number;
  widgets: Widget[];
}

// ---------------------------------------------------------------------------
// Capital stack — a company's ranked capital structure as an OVERLAY.
//
// A tranche references an existing model series (item/driver name) for its
// claim/notional and rate — it never copies the numbers. Seniority orders the
// waterfall; the analysis (capitalstack.analyzeCapitalStack) derives claims,
// recovery, coverage, residual-to-common, blended cost, and dilution per period.
// ---------------------------------------------------------------------------

export type TrancheKind =
  | "senior_debt"
  | "subordinated_debt"
  | "convertible"
  | "preferred"
  | "common";

/** One layer of the capital structure. Claims/rates reference model series by name. */
export interface Tranche {
  id: string;
  name: string;
  kind: TrancheKind;
  /** Priority rank — lower is more senior (paid first). Ties pay pari-passu. */
  seniority: number;
  /** Item/driver name giving this tranche's claim (face/liquidation pref) per period. */
  notionalRef?: string;
  /** Scalar coupon/dividend rate (annual), for blended cost of capital. */
  rate?: number;
  /** …or an item/driver name for a per-period rate series (wins over `rate`). */
  rateRef?: string;
  /** Item/driver name for the share count (residual/common, or converts-as-equity). */
  sharesRef?: string;
  /** Convertible strike; shares added when treated as equity = notional / price. */
  conversionPrice?: number;
  /** 1 = treat this convertible as look-through equity (dilutes); 0 = face-value debt. */
  convertAsEquity?: number;
}

/** A stored capital structure: value the claims run against, plus ranked tranches. */
export interface CapitalStack {
  /** Item/driver names whose sum is the asset value claims are paid from. */
  assetRefs: string[];
  tranches: Tranche[];
}

/** The top-level container — the whole model as one serializable object. */
export interface Model {
  id: string;
  meta: ModelMeta;
  timeline: Timeline;
  items: LineItem[];
  drivers: Driver[];
  scenarios: Scenario[];
  /** Optional persisted chart definitions. Absent on pre-visualization models. */
  charts?: Chart[];
  /** Optional persisted dashboard layout. Absent on pre-visualization models. */
  dashboard?: Dashboard;
  /** Optional persisted capital structure (ranked tranches over referenced series). */
  capitalStack?: CapitalStack;
}

/** A computed result: every item's series under a given scenario. */
export interface ComputedModel {
  scenarioId: string;
  /** itemId -> per-period computed values. */
  series: Record<string, number[]>;
  /**
   * driverId -> per-period driver values under this scenario (base with overrides
   * applied). Lets adapters resolve a name to an item OR a driver — mirroring the
   * engine's name resolution — without recomputing driver expansion themselves.
   */
  drivers: Record<string, number[]>;
  /** Whether the iterative solver reached convergence (for circular models). */
  converged: boolean;
  iterations: number;
  /**
   * Item ids a formula reached *forward* in time to during an as-of compute —
   * look-ahead-bias violations. Present only under `asOf` and only when non-empty;
   * a backtest relying on the compute must refuse to run when this is set.
   */
  lookAhead?: string[];
}

/**
 * A concise, self-declared description of what an edit operation changed. Each
 * operation states its own intent (not a computed diff), so adapters can report
 * "what changed" without echoing or diffing the whole model.
 */
export interface ChangeSummary {
  op: "add" | "update" | "remove" | "rename";
  entity:
    | "item"
    | "driver"
    | "scenario"
    | "timeline"
    | "chart"
    | "widget"
    | "model"
    | "tranche"
    | "capital_stack";
  /** The affected entity's id, when it has one. */
  id?: string;
  /** The affected entity's (new) name, when applicable. */
  name?: string;
  /** Fields that were changed, for an update. */
  fields?: string[];
  /** Free-text elaboration, e.g. "renamed from X" or "trimmed 16 -> 8 periods". */
  detail?: string;
}

export type Severity = "error" | "warning" | "info";

export interface ValidationIssue {
  severity: Severity;
  code: string;
  message: string;
  /** Item or driver the issue points at, when applicable. */
  targetId?: string;
  period?: number;
}
